# Copyright 2021 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build Klor w/ nice_nano_v2'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["klor_left","klor_right"]'
      alphas: '["qwerty"]'
      nav: '["default"]'
      clipboard: '["default"]'
      layers: '["default"]'
      custom_config: '["#define MIRYOKU_KLUDGE_MOUSEKEYSPR\n#define MIRYOKU_TAP_QWERTY\n#define MIRYOKU_EXTRA_COLEMAKDH"]'
      kconfig: '["CONFIG_ZMK_MOUSE=y\nCONFIG_EC11=y\nCONFIG_EC11_TRIGGER_GLOBAL_THREAD=y\nCONFIG_ZMK_DISPLAY=y\nCONFIG_ZMK_RGB_UNDERGLOW=y\nCONFIG_WS2812_STRIP=y\nCONFIG_ZMK_RGB_UNDERGLOW_HUE_START=309\nCONFIG_ZMK_RGB_UNDERGLOW_SAT_START=100\nCONFIG_ZMK_RGB_UNDERGLOW_BRT_START=25\nCONFIG_ZMK_RGB_UNDERGLOW_ON_START=y\nCONFIG_ZMK_BACKLIGHT_AUTO_OFF_USB=n\nCONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=n"]'
      branches: '["zmkfirmware/zmk/main petejohanson/zmk/features/pointer-hid-core"]'
